"""Make portfolio_id nullable in transactions

Revision ID: 038329da6f79
Revises: 3466a9d9bec7
Create Date: 2025-04-11 17:26:44.040335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038329da6f79'
down_revision = '3466a9d9bec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
