"""make stock_id nullable

Revision ID: 605caa31e2f7
Revises: 038329da6f79
Create Date: 2025-04-15 17:35:25.109435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605caa31e2f7'
down_revision = '038329da6f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
